FROM node:20.19.4

ENV APP_PORT 3000

ENV TZ=Europe/Berlin

# ARG API_KEY
# ENV API_KEY=${API_KEY}

# ARG FIREBASE_PROJECT_ID
# ENV FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}

# ARG FIREBASE_PRIVATE_KEY
# ENV FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}

# ARG FIREBASE_CLIENT_EMAIL
# ENV FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}

# ARG APP_VERSION
# ENV APP_VERSION=${APP_VERSION}

# ARG CRON
# ENV CRON=${CRON}

# ARG JWT_SECRET
# ENV JWT_SECRET=${JWT_SECRET}

# ARG SMTP_HOST
# ENV SMTP_HOST=${SMTP_HOST}

# ARG SMTP_PORT
# ENV SMTP_PORT=${SMTP_PORT}

# ARG SMTP_TOKEN
# ENV SMTP_TOKEN=${SMTP_TOKEN}

EXPOSE 3000

WORKDIR /usr/src/app

RUN npm i typescript -g --loglevel notice
RUN npm i @nestjs/cli -g --loglevel notice

COPY package.json .
COPY . .

RUN npm install --loglevel notice --unsafe-perm

RUN npm run build

CMD [ "npm", "run", "start:prod" ]