name: CI

on:
  push

env:
  API_KEY: ${{ secrets.API_KEY }}
  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
  FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
  FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    outputs:
      branch_name: ${{ steps.branch-name.outputs.current_branch }}

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Branch Name
        uses: tj-actions/branch-names@v5.1
        id: branch-name

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/tobi2k/tippspiel:${{ steps.branch-name.outputs.current_branch }}
  
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and pull image
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker pull ghcr.io/tobi2k/tippspiel:${{ needs.build.outputs.branch_name }}
            docker stop top-tips-server
            docker rm top-tips-server
            docker run -d --restart unless-stopped --network host --name=top-tips-server --env API_KEY=${{ env.API_KEY }} --env FIREBASE_PROJECT_ID=${{ env.FIREBASE_PROJECT_ID }} --env FIREBASE_PRIVATE_KEY=${{ env.FIREBASE_PRIVATE_KEY }} --env FIREBASE_CLIENT_EMAIL=${{ env.FIREBASE_CLIENT_EMAIL }} ghcr.io/tobi2k/tippspiel:${{ needs.build.outputs.branch_name }}
          host: ${{ secrets.HOST }}
          user: root
          key: ${{ secrets.PRIVATE_KEY}}
